[profile.default]
src = "vibe/src"
test = "vibe/tests"
script = "vibe/scripts"
out = "vibe/out"
cache_path = "vibe/cache"
libs = ["vibe/lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options